### ISSUE TITLE
老铁啊，请教个问题

### ISSUE THREAD

**Issue by ghost** [winar-jin/JavaScript30-Challenge#2]
document.documentElement.style.setProperty(`--${this.name}`, this.value + suffix)

这行代码中，`--${this.name}`模板语法为什么放一个--。

**Comment by phoebeCodeSpace** [comment]
CSS 变量[var(--xxx)](https://developer.mozilla.org/zh-CN/docs/Web/CSS/Using_CSS_variables)

**Comment by winar-jin** [comment]
是的，是CSS 变量[var(--xxx)](https://developer.mozilla.org/zh-CN/docs/Web/CSS/Using_CSS_variables)。 @xiaohangJose
