### ISSUE TITLE
为什么要判断propertyName === transform 呢？

### ISSUE THREAD

**Issue by niusz** [winar-jin/JavaScript30-Challenge#5]
不写的话，代码也能实现呀

**Comment by winar-jin** [comment]
这里更多的是性能上的考虑。例如当 `e.propertyName` 不等于 `transform` 时，也就是说这并不是我们所期望的事件，直接将它 `return` 出去，就不必再走接下来的流程了。是一种考虑，如果从最终实现效果上来说确实不写该条判断，不影响最终的效果执行。🙏
